name: Security Pipeline
on: [push]

jobs:
  security-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install dockerfile
      - name: Run Auditor
        run: python auditor.py

  build-image:
    needs: security-verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Registry
        # CORRECCIÓN: Usamos DOCKER_USERNAME para que coincida con el secreto que creaste
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          docker build -t ryshar/mi-app:1.0 .
          docker push ryshar/mi-app:1.0
