name: Security Pipeline
on: [push]

jobs:
  security-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Asegúrate de que este es el nombre correcto de la librería que usa tu auditor.py
          pip install dockerfile-parse 

      - name: Run Auditor
        run: python auditor.py

  build-image:
    needs: security-verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files (Diagnóstico)
        run: ls -la # Esto nos dirá si el Dockerfile existe y cómo se llama exactamente

      - name: Login to Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push
        run: |
          # Si el archivo se llama Dockerfile (sin extensión), esto funcionará:
          docker build -t ryshar/mi-app:1.0 .
          docker push ryshar/mi-app:1.0
